version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    command: mongod --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles

  app:
    build: .
    ports:
      - '3000:3000'
    command: yarn start
    links:
      - mongodb
